// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// CompressorI is an autogenerated mock type for the CompressorI type
type CompressorI struct {
	mock.Mock
}

type CompressorI_Expecter struct {
	mock *mock.Mock
}

func (_m *CompressorI) EXPECT() *CompressorI_Expecter {
	return &CompressorI_Expecter{mock: &_m.Mock}
}

// Compress provides a mock function with given fields: _a0
func (_m *CompressorI) Compress(_a0 []byte) ([]byte, error) {
	ret := _m.Called(_a0)

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte) ([]byte, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func([]byte) []byte); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CompressorI_Compress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Compress'
type CompressorI_Compress_Call struct {
	*mock.Call
}

// Compress is a helper method to define mock.On call
//   - _a0 []byte
func (_e *CompressorI_Expecter) Compress(_a0 interface{}) *CompressorI_Compress_Call {
	return &CompressorI_Compress_Call{Call: _e.mock.On("Compress", _a0)}
}

func (_c *CompressorI_Compress_Call) Run(run func(_a0 []byte)) *CompressorI_Compress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte))
	})
	return _c
}

func (_c *CompressorI_Compress_Call) Return(_a0 []byte, _a1 error) *CompressorI_Compress_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CompressorI_Compress_Call) RunAndReturn(run func([]byte) ([]byte, error)) *CompressorI_Compress_Call {
	_c.Call.Return(run)
	return _c
}

// Decompress provides a mock function with given fields: _a0
func (_m *CompressorI) Decompress(_a0 []byte) ([]byte, error) {
	ret := _m.Called(_a0)

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte) ([]byte, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func([]byte) []byte); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CompressorI_Decompress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Decompress'
type CompressorI_Decompress_Call struct {
	*mock.Call
}

// Decompress is a helper method to define mock.On call
//   - _a0 []byte
func (_e *CompressorI_Expecter) Decompress(_a0 interface{}) *CompressorI_Decompress_Call {
	return &CompressorI_Decompress_Call{Call: _e.mock.On("Decompress", _a0)}
}

func (_c *CompressorI_Decompress_Call) Run(run func(_a0 []byte)) *CompressorI_Decompress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte))
	})
	return _c
}

func (_c *CompressorI_Decompress_Call) Return(_a0 []byte, _a1 error) *CompressorI_Decompress_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CompressorI_Decompress_Call) RunAndReturn(run func([]byte) ([]byte, error)) *CompressorI_Decompress_Call {
	_c.Call.Return(run)
	return _c
}

// NewCompressorI creates a new instance of CompressorI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCompressorI(t interface {
	mock.TestingT
	Cleanup(func())
}) *CompressorI {
	mock := &CompressorI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
